import { db } from '../src/db.js'

await new Promise<void>(resolve => setTimeout(resolve, 1000))

await db.query(`create table if not exists users (
  id     integer generated by default as identity,
  amount integer default 0 not null
)`)

await db.$pool.end()